### PR TITLE
Helm chart improvements

### PR DESCRIPTION
**Pull request by sidineyc**
To address the points mentioned at issue #63

### CODE REVIEW

**Comment by terinjokes** [comment]
I'll consider a PR without the CRD additions.

**Comment by sidineyc** [comment]
may I ask why? It's better to have it defined on the chart itself, specially once you are deploying with tools such as ArgoCD, otherwise one needs to manually bring definition of the CRDs.

I can add a condition to deploy the CRDs and  set the default value to false, does that work for you?

**Comment by terinjokes** [comment]
Deploying CRDs with Helm does not work as one expects, and causes support issues later, as Helm does not keep it synchronized with the rest of the chart. It is better for operators to be an active participant in the installing CRD activity.

**Comment by sidineyc** [comment]
I see your point, still think would be better to have the chance to deploy or not directly from the chart. And by leaving the default value to false, just those who really want it can enable.

If you're still not up for it, I will remove the CRDs and push the changes later.

**Comment by mfinelli** [comment]
The official cert-manager chart provides an option `installCRDs` (default false) for those who prefer to install them with helm (https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L44)

**Comment by vladtara** [comment]
How long we should wait to merge that pr to the trunk? Everything looks good. Let's merge pr!!

**Comment by zifeo** [comment]
@terinjokes I support having the option to install them with the chart. @sidineyc WDYT?

**Pull request closed without merging**
