### PR TITLE
Added secret reference and OriginIssuer

### PR DESCRIPTION
**Pull request by nassah**
Providing Helm charts as complete as possible, avoiding manual creation of secret and OriginIssuer.
This makes it possible to handle components (secret + OriginIssuer) for the origin-ca-issuer as part of the release itself.

- Updated README.md
- Adjusted _helpers.tpl (to be in-line with current setup)
- Adjusted values.yaml (including some documentation)
- Added origin-issuer.yaml
-  secretkeyref.yaml

These changes have been tested, if some names are not very appropriate.. feel free to add comments.

Thank you

### CODE REVIEW

**Review by sanderv32 — APPROVED** [review]

**Comment by sanderv32** [comment]
+1

**Comment by terinjokes** [comment]
This is a chart to deploy and upgrade the issuer controller. I think it makes sense to deploy Issuers and Certificates as part of the application and its chart.

If you have a compelling use case otherwise, please open an issue to discuss.

**Comment by nassah** [comment]
> This is a chart to deploy and upgrade the issuer controller. I think it makes sense to deploy Issuers and Certificates as part of the application and its chart.
> 
> If you have a compelling use case otherwise, please open an issue to discuss.

We do not have a separate application, the OriginIssuer and the secret reference are only relevant with the controller itself, hence referring to it's 'components'. If there is no need then I will find another way.... I did spent some time on this, a bit sad to see it closed like this.

Thanks

**Comment by terinjokes** [comment]
The issuer is not a component of the controller. They're used by applications to configure cert-manager to create certificates for the application.

**Comment by nassah** [comment]
> The issuer is not a component of the controller. They're used by applications to configure cert-manager to create certificates for the application.

Ah maybe I do not understand, so what you are saying is I can use the OriginIssuer (`cert-manager.k8s.cloudflare.com/v1`) without **_this_** controller installed (corresponding CRDs)?

Renewing certificates should be an 'application' with dependencies on cert-manager and **_this_** controller because we want to renew Cloudflare certificates?

Since imo the OriginIssuer is also being used to `configure cert-manager to create certificates for the application`  made possible by definitions of  **_this_** controller ? 

For your consideration. we are not requesting certificate(s) per application.

Thanks in advance

**Comment by nassah** [comment]
The concept to me is clear, Thanks

**Pull request closed without merging**
