### PR TITLE
Fixes #2

### LINKED ISSUE #2: Helm chart
Any plans to provide a Helm chart?

This would greatly simplify automated deployment.

### PR DESCRIPTION
**Pull request by abhi1693**
This PR uses Helm v3 to deploy the chart. I also wrote a workflow to lint and test the chart since I do not have permissions here, I could not push. So, adding the code to this PR

.github/workflows/helm-charts-test.yaml
```
name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
```

ct.yaml
```
remote: origin
target-branch: trunk
chart-dirs:
  - charts
helm-extra-args: --timeout 300s
debug: true
```

### CODE REVIEW

**Comment by abhi1693** [comment]
Please don't judge too much into this. I only spent 10 minutes writing this code. If anyone needs a change here, let me know.

**Comment by terinjokes** [comment]
Thanks for your contribution. I'm going to leave this open for now as I think there might need to be some changes as I work on putting together a release. I hope that's fine by you.

**Comment by abhi1693** [comment]
It works for me. I use Cloudflare SSL with terraforming on Kubernetes these days. Although I'm looking forward to a release on this repo. It will make our DevOps guy's life easier.

**Comment by abhi1693** [comment]
I forgot to mention previously, but I made changes to your CRD to conform with Kubernetes v1.19. Take a look at https://github.com/abhi1693/origin-ca-issuer/blob/trunk/charts/templates/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml

**Comment by terinjokes** [comment]
The CRDs are auto-generated by kubebuilder. I'm currently using `apiextensions.k8s.io/v1beta1` to have a wider compatibility range: you can enable this on 1.19.

**Comment by abhi1693** [comment]
I have a hardened cluster that does not let me run incompatible/deprecated APIs so I updated it.

**Comment by terinjokes** [comment]
I can't stop you from changing it locally, of course.

I'll be increasing this project to `apiextensions.k8s.io/v1` soon, after more testing. In the meantime, any derived templates in this repository should match.

**Review by matthewdaltonditto — APPROVED** [review]

**Comment by terinjokes** [comment]
CRD on master is now v1, and a Helm chart exists to manage the deployment, service accounts and RBAC.

**Pull request closed without merging**
